version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"

install:
  - cmd: "%PYTHON%\\python.exe setup.py install"
  - cmd: "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - cmd: "%PYTHON%/Scripts/nosetests.exe"

build: off
